config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  root "static_pages#home"
  get "/contact",    to: "static_pages#contact"
  get "/help",       to: "static_pages#help"
  get "/signup",     to: "users#new"
  get "/login",      to: "sessions#new"
  post "/login",     to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"

  resources :events, :users
  resources :account_activations, only: [ :edit ]
  resources :password_resets, only: [ :new, :create, :edit, :update ]
  resources :price_alerts, only: [ :create, :destroy ]
  get "price_alerts", to: "static_pages#home"
end

app/models/price_alert.rb
class PriceAlert < ApplicationRecord
  belongs_to :user
  belongs_to :event
  default_scope -> {
    joins(:event).order("events.date")
  }
  validates :alert_price, presence: true, numericality: { only_integer: true }

  after_destroy :destroy_event_if_no_alerts

  private
    def destroy_event_if_no_alerts
      event.destroy if event.price_alerts.empty?
    end
end

app/controllers/price_alerts_controller.rb
require "json"
require "uri"

class PriceAlertsController < ApplicationController
  include SessionsHelper
  include PriceAlertsHelper
  before_action :logged_in_user, only: [ :create, :destroy ]
  before_action :correct_user, only: :destroy

  # def index
  #   @price_alerts = PriceAlert.where(user_id: current_user)
  # end

  # def show
  #   @price_alert = PriceAlert.find(params[:id])
  # end

  # def new
  #   @price_alert = PriceAlert.new
  # end

  def create
    stubhub_url = alert_params[:stubhub_url]
    unless stubhub_url.match(/\/event\/(\d+)/)
      flash[:danger] = "Incorrect StubHub url entered, please copy the entire event including the event id"
      redirect_to root_url
      return
    end
    stubhub_id = stubhub_url.match(/\/event\/(\d+)/)[1]

    event = Event.find_by(stubhub_id: stubhub_id)
    if event
      puts "Event already exists in the database"
    else
      event_object = fetch_event_data(stubhub_url)
      if event_object
        event = Event.create!(event_object)
      else
        flash[:danger] = "Invalid stubhub url, please check if the event has already passed"
        redirect_to root_url and return
      end
    end


    alert_user = alert_params[:alert_price].to_i > event.live_price_cad
    @price_alert = current_user.price_alerts.build(
                                                    alert_price: alert_params[:alert_price],
                                                    event_id: event.id,
                                                    alert_user: alert_user)
    if @price_alert.save
      flash[:success] = "Price alert saved!"
      redirect_to root_url
    else
      puts @price_alert.errors.full_messages  # Debug output
      @price_alerts = PriceAlert.where("user_id = ?", current_user)
      render "static_pages/home", status: :unprocessable_entity
    end
  end

  # def edit
  #   @price_alert = PriceAlert.find(params[:id])
  # end

  # def update
  #   @price_alert = PriceAlert.find(params[:id])

  #   if @price_alert.update(alert_params)
  #     redirect_to @price_alert
  #   else
  #     render :edit, status: :unprocessable_entity
  #   end
  # end

  def destroy
    @price_alert.destroy
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove("price-alert-#{@price_alert.id}") }
      format.html { redirect_to root_path, status: :see_other }
    end
  end

  private
  def alert_params
    params.require(:price_alert).permit(:alert_price, :stubhub_url)
  end

  def correct_user
    @price_alert = current_user.price_alerts.find_by(id: params[:id])
    redirect_to root_url, status: :see_other if @price_alert.nil?
  end
end

app/helpers/price_alerts_helper.rb
require "net/http"
require "json"

module PriceAlertsHelper
  def fetch_event_data(url)
    response = HTTParty.get(url)
    json_response = response.parsed_response
    parsed_json = json_response.match(/<script id="index-data" type="application\/json">\s*(.*?)\s*<\/script>/)[1]
    json_data = JSON.parse(parsed_json)
    if json_data["errorMessage"] != "Page Not Found"
      currency = json_data["grid"]["formattedMinPrice"][0]
      exchange_rate = currency == "C" ? 1 : usd_to_cad
      {
        name: json_data["eventName"],
        date: json_data["formattedEventDateTime"],
        venue: json_data["venueName"],
        live_price_cad: (json_data["grid"]["minPrice"] * exchange_rate).round,
        url: url,
        stubhub_id: json_data["eventId"],
        image_url: json_data["categoryImageUrl"]
      }
    else
      puts "-------No matching JSON data found------"
      nil
    end
  end
end

private
  def usd_to_cad
    uri = URI("https://api.exchangerate-api.com/v4/latest/usd")
    response = Net::HTTP.get(uri)
    json = JSON.parse(response)
    json["rates"]["CAD"]
  end

app/views/price_alerts/_form.html.erb
<% if @price_alert.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@price_alert.errors.count, "error") %> prohibited this price_alert from being saved:</h2>
    <ul>
      <% @price_alert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: price_alert) do |form| %>
    <div>
        <%= form.label :event_id %>
        <%= form.text_field :event_id %>
    </div>
    <div>
        <%= form.label :user_id %>
        <%= form.text_field :user_id %>
    </div>
    <div>
        <%= form.label :alert_price %>
        <%= form.number_field :alert_price %>
    </div>
    <%= form.submit %>
<% end %>

app/views/price_alerts/_price_alert.html.erb
<%= turbo_frame_tag "price-alert-#{price_alert.id}", class: "cs-item #{price_alert.alert_user ? "alert-user" : ""}" do %>
    <a href="<%= price_alert.event.url %>" target="_blank" class="cs-link">
        <picture class="cs-picture" aria-hidden="true">
          <%= image_tag(price_alert.event.image_url) %>
        </picture>
        <div class="cs-flex">
            <span class="cs-date"><%= image_tag "svgs/calendar.svg" %><%= price_alert.event.date.strftime("%b %d, %Y") %></span>
            <h3 class="cs-h3"><%= price_alert.event.name %></h3>
            <ul class="cs-item-text">
              <li> <strong><%= image_tag 'svgs/map-pin' %> </strong> <%= price_alert.event.venue %> </li>
              <li> <strong>Live Price: </strong> $<%= price_alert.event.live_price_cad %> </li>
              <li> <strong>Alert Price: </strong> $<%= price_alert.alert_price %> </li>
            </ul>
        </div>
    </a>
    <%= button_to price_alert_path(price_alert, format: :turbo_stream), class: "icon-trash", method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
      <%= image_tag 'svgs/trash.svg', alt: 'Delete icno', width: 32, height: 32 %>
    <% end %>
    <%= image_tag 'svgs/pencil.svg', alt: 'Edit icon', width: 32, height: 32, class: "icon-edit", id: "edit-#{price_alert.id}" %>
    <form class="price-edit-form hidden" action="<%= price_alert_path(price_alert) %>" method="post" data-turbo-frame="price_alert_<%= price_alert.id %>">
      <input type="hidden" name="_method" value="patch">
      <input type="number" name="price_alert[alert_price]" value="<%= price_alert.alert_price %>" step="0.01">
      <button type="submit" class="btn btn-primary">Save</button>
      <button type="button" class="btn btn-secondary cancel-edit" data-id="<%= price_alert.id %>">Cancel</button>
  </form>
<% end %>

app/views/price_alerts/edit.html.erb
<section class="temp-pages">
    <div class="container">
        <h1>Edit Price Alert</h1>
        <%= render "form", price_alert: @price_alert %>
    </div>
</section>

app/views/price_alerts/index.html.erb
<% provide(:title, "Home") %>

<div class="container">
    <%= form_with do |form| %>
        <%= form.search_field :query %>
        <%= form.submit "Add Price Alert" %>
    <% end %>
    <%= link_to 'Add Price Alert', new_price_alert_path %>
    <div><%= link_to 'Add New Event', new_event_path %></div>
    <h2 class="cs-title">Sports</h2>
    <ul class="price-alerts">
        <%= render @price_alerts %>
    </ul>
</div>
                                

app/views/price_alerts/new.html.erb
<section class="temp-pages">
    <div class="container">
        <% if logged_in? %>
            <h1>Add Price Alert</h1>
            <%= render "form", price_alert: @price_alert %>
        <% else%>
            <%= render "logged_out_home" %>
        <% end %>
    </div>
</section>

app/views/price_alerts/show.html.erb
<section class="temp-pages">
    <div class="container">
        <% provide :title, @price_alert.event.name %>
        
        <h1>Show a specific price alert</h1>
        <h3><%= @price_alert.event.name %></h3>
        <div> <strong>Date: </strong> <%= @price_alert.event.date %> </div>
        <div> <strong>Venue: </strong> <%= @price_alert.event.venue %> </div>
        <div> <strong>Live Price: </strong> <%= @price_alert.event.live_price_cad %> </div>
        <div> <strong>Alert Price: </strong> <%= @price_alert.alert_price %> </div>
        <div> <strong>Event Type: </strong> <%= @price_alert.event.event_type %> </div>
        <div> <strong>User Email: </strong> <%= @price_alert.user.email %> </div>

        <ul>
            <li><%= link_to "Edit Alert", edit_price_alert_path(@price_alert) %></li>
            <li>
                <%= link_to "Delete Alert", price_alert_path(@price_alert), data: {
                            turbo_method: :delete,
                            turbo_confirm: "Are you sure?"
                            } %>

            </li>
        </ul>
    </div>
</section>