config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  root "static_pages#home"
  get "/contact",    to: "static_pages#contact"
  get "/help",       to: "static_pages#help"
  get "/signup",     to: "users#new"
  get "/login",      to: "sessions#new"
  post "/login",     to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"

  resources :events, :users
  resources :account_activations, only: [ :edit ]
  resources :password_resets, only: [ :new, :create, :edit, :update ]
  resources :price_alerts, only: [ :create, :destroy ]
  get "price_alerts", to: "static_pages#home"
end

app/models/event.rb
require "date"

class Event < ApplicationRecord
  has_many :price_alerts, dependent: :destroy

  validates :name, presence: true
  validates :date, presence: true
  validates :venue, presence: true
  validates :live_price_cad, presence: true, numericality: { only_integer: true }
  scope :expired, -> { where("updated_at < ?", 15.minutes.ago) }
  scope :completed, -> { where("date < ?", Date.today) }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :logged_in_user, only: [ :new, :create ]
  def index
    @events = Event.all.paginate(page: params[:page])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)

    if @event.save
      redirect_to @event
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to @event
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to events_path, status: :see_other
  end

    private
    def event_params
      params.require(:event).permit(:name, :date, :venue, :live_price_cad,
                                    :live_price_usd, :url, :stubhub_id, :image_url, :event_type)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<li class= "card" id="event-%{event.id}">
    <h3><%= event.name %></h3>
    <%= image_tag(event.image_url) %>
    <div> <strong>Date: </strong> <%= event.date %> </div>
    <div> <strong>Venue: </strong> <%= event.venue %> </div>
    <div> <strong>Price: </strong> <%= event.live_price_cad %> </div>
    <div> <strong>Event Type: </strong> <%= event.event_type %> </div>
    <div><%= link_to "Show Event", event %></div>
    <%= link_to "Edit Event", edit_event_path(event) %>
    <div>
        <%= link_to "Delete Event", event_path(event), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                    } %>
    </div>
</li>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
    <div>
        <%= form.label :name %>
        <%= form.text_field :name %>
        <% event.errors.full_messages_for(:name).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <div>
        <%= form.label :date %>
        <%= form.date_select :date %>
    </div>
    <div>
        <%= form.label :venue %>
        <%= form.text_field :venue %>
    </div>
    <div>
        <%= form.label :live_price_cad %>
        <%= form.number_field :live_price_cad %>
    </div>
    <div>
        <%= form.label :live_price_usd %>
        <%= form.number_field :live_price_usd %>
    </div>
    <div>
        <%= form.label :image_url %>
        <%= form.text_field :image_url %>
    </div>
    <div>
        <%= form.label :event_type %>
        <%= form.text_field :event_type %>
    </div>
    <div>
        <%= form.label :stubhub_id %>
        <%= form.text_field :stubhub_id %>
    </div>
    <%= form.submit %>
<% end %>

app/views/events/edit.html.erb
<section class="temp-pages">
    <div class="container">
        <h1>Edit this event</h1>
        <%= render "form", event: @event %>
    </div>
</section>

app/views/events/index.html.erb
<% provide(:title, "Events")%>
<section class="temp-pages">
    <div class="container">
        <h1>All Events</h1>
        <ul class="events">
            <%= render @events %>
        </ul>
        <%= will_paginate @events %>
    </div>
</section>

app/views/events/new.html.erb
<section class="temp-pages">
    <div class="container">
        <h1>Create a New Event!</h1>
        <%= render "form", event: @event %>
    </div>
</section>

app/views/events/show.html.erb
<section class="temp-pages">
    <div class="container">
        <h1>Show a specific event details</h1>
        <h3><%= @event.name %></h3>
        <div> <strong>Date: </strong> <%= @event.date %> </div>
        <div> <strong>Venue: </strong> <%= @event.venue %> </div>
        <div> <strong>Price: </strong> <%= @event.live_price_cad %> </div>
        <div> <strong>Event Type: </strong> <%= @event.event_type %> </div>

        <ul>
            <li><%= link_to "Edit Event", edit_event_path(@event) %></li>
            <li>
                <%= link_to "Delete Event", event_path(@event), data: {
                            turbo_method: :delete,
                            turbo_confirm: "Are you sure?"
                            } %>

            </li>
        </ul>
    </div>
</section>