config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  mount Sidekiq::Web => "/sidekiq"

  root "static_pages#home"
  get "/contact",    to: "static_pages#contact"
  get "/help",       to: "static_pages#help"
  get "/signup",     to: "users#new"
  get "/login",      to: "sessions#new"
  post "/login",     to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"

  resources :events, :users
  resources :account_activations, only: [ :edit ]
  resources :password_resets, only: [ :new, :create, :edit, :update ]
  resources :price_alerts, only: [ :create, :destroy ]
  get "price_alerts", to: "static_pages#home"
end

app/views/layouts/_footer.html.erb
<!-- ============================================ -->
<!--                   Footer                     -->
<!-- ============================================ -->

<footer id="cs-footer-105">
    <div class="cs-container">
        <ul class="cs-ul">
            <li class="cs-li">
                <%= link_to 'Home', root_path, class: "cs-link" %>
            </li>
            <li class="cs-li">
                <%= link_to 'Help', help_path, class: "cs-link" %>
            </li>
            <li class="cs-li">
                <%= link_to 'Sign Up', signup_path, class: "cs-link" %>
            </li>
            <li class="cs-li">
                <%= link_to 'Contact', contact_path, class: "cs-link" %>
            </li>
            <li class="cs-li">
                <a href="mailto:stubhub.alerts@gmail.com" class="cs-link">stubhub.alerts@gmail.com</a>
            </li>
        </ul>
        <div class="cs-bottom">
            <span class="cs-copyright"><%= Time.now.year %> Copyright</span>
            <a class="cs-social-link" aria-label="visit google profile" href="#">
                <img aria-hidden="true" loading="lazy" decoding="async" src="https://csimg.nyc3.digitaloceanspaces.com/Social/google.svg" alt="google" width="11" height="11">
            </a>
            <a class="cs-social-link" aria-label="visit facebook profile" href="#">
                <img aria-hidden="true" loading="lazy" decoding="async" src="https://csimg.nyc3.digitaloceanspaces.com/Social/Facebook.svg" alt="facebook" width="6" height="11">
            </a>
            <a class="cs-social-link" aria-label="visit instagram profile" href="#">
                <img aria-hidden="true" loading="lazy" decoding="async" src="https://csimg.nyc3.digitaloceanspaces.com/Social/instagram.svg" alt="instagram" width="11" height="11">
            </a>
        </div>
    </div>
</footer>
                                

app/views/layouts/_header.html.erb
<header id="cs-navigation">
  <div class="cs-container">
    <%= link_to root_path, class: "cs-logo" do %>
      <%= image_tag 'logo.svg' %>
    <% end%>
    <nav class="cs-nav" role="navigation">
      <!--Mobile Nav Toggle-->
      <button class="cs-toggle" aria-label="mobile menu toggle">
        <div class="cs-box" aria-hidden="true">
          <span class="cs-line cs-line1" aria-hidden="true"></span>
          <span class="cs-line cs-line2" aria-hidden="true"></span>
          <span class="cs-line cs-line3" aria-hidden="true"></span>
        </div>
      </button>

      <div class="cs-ul-wrapper">
        <ul id="cs-expanded" class="cs-ul" aria-expanded="false">
          <li class="cs-li">
              <%= link_to 'Home', root_path, class: "cs-li-link cs-active" %>
          </li>
          <li class="cs-li">
              <%= link_to 'Help', help_path, class: "cs-li-link" %>
          </li>
          <% if logged_in? %>
            <li class="cs-li">
              <%= link_to "Profile", edit_user_path(current_user), class: "cs-li-link" %>
            </li>
            <li class="cs-li">
              <%= button_to "Log out", logout_path, method: :delete, data: { turbo: true },
                                                    class: "cs-drop-button cs-li-link" %>
            </li>
          <% else %>
            <%= link_to 'Log in/Sign up', login_path, class: "cs-button-solid cs-nav-button" %>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>
</header>

<% if false %>
    <% if logged_in? %>
      <li class="cs-li cs-dropdown" tabindex="0">
        <span class="cs-li-link">Account
            <img class="cs-drop-icon" src="https://csimg.nyc3.cdn.digitaloceanspaces.com/Icons/down-red.svg" alt="dropdown icon" width="15" height="15" decoding="async" aria-hidden="true">
        </span>
        <ul class="cs-drop-ul">
            <li class="cs-drop-li">
              <%= link_to "Profile", edit_user_path(current_user), class: "cs-li-link cs-drop-link" %>
            </li>
            <li class="cs-drop-li">
              <%= button_to "Log out", logout_path, method: :delete, data: { turbo: true },
                                                    class: "cs-drop-button cs-li-link cs-drop-link" %>
            </li>
        </ul>
      </li>
    <% else %>
      <%= link_to 'Log in/Sign up', login_path, class: "cs-button-solid cs-nav-button" %>
    <% end %>
<% end %>

app/views/layouts/_shim.html.erb
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title)? "StubHub Price Tracker | #{yield(:title)}" : "StubHub Price Tracker" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json.erb">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= turbo_include_tags %>
    <%= render 'layouts/shim' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>